export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAIL = "USER_INFO_FAIL"

export const REPOS_INFO_REQUEST = "REPOS_INFO_REQUEST"
export const REPOS_INFO_SUCCESS = "REPOS_INFO_SUCCESS"
export const REPOS_INFO_FAIL = "REPOS_INFO_FAIL"